#!/usr/bin/env bash
# Line coverage per codebase (global rule #29), the gate's coverage step (gate-core.sh runs this file).
#
# Exit codes:  0  every codebase that exists is measured and at or above the threshold
#              1  the tests are red, or a measured codebase is below the threshold
#              3  a codebase exists but is NOT measured — which blocks, exactly like a failure
#                 (#29: an unmeasured codebase does not count as passing)
#
# The codebases (ADR-0002): the .NET API and agent, and the web app. Each is measured here from the phase
# that adds it; until its measurement is written, its mere presence is NOT MEASURED, so new code can never
# slip past this step as "n/a".
#
# THE EXCLUSION LIST (global #29: generated code only, one place, a reason per entry):
#   **/Data/Migrations/*.cs   EF Core migrations and the model snapshot, generated by `dotnet ef`.
#   **/obj/**                 compiler output: source generators' code (the [GeneratedRegex] implementations).
#   tests/**                  the tests themselves (they are the measurement).
#
# Out of scope, stated: the scripts under scripts/ are gate tooling, not product. The shared ones are measured in
# the configuration repository; this repository's own (backcompat_scan.py) is tested here. Their tests
# (scripts/tests) run, and red blocks.
set -uo pipefail

root="$(git rev-parse --show-toplevel 2>/dev/null)" || { echo "not inside a git repository" >&2; exit 2; }
cd "$root" || exit 2
min="${COVERAGE_MIN:-80}"
status=0
worse() { if [ "$1" != 0 ] && { [ "$status" = 0 ] || [ "$1" = 3 ]; }; then status="$1"; fi; }

echo "▶ gate tool tests (scripts/tests)"
log="$(mktemp)"
if python3 -m unittest discover -s scripts/tests -p 'test_*.py' >"$log" 2>&1; then
  echo "  ✓ $(grep -E '^Ran ' "$log")"
else
  tail -20 "$log" | sed 's/^/  /'
  echo "  ✗ the tests are red"
  worse 1
fi
rm -f "$log"
find scripts -name __pycache__ -prune -exec rm -rf {} + 2>/dev/null

# One .NET codebase: its test project and the assemblies it measures. The API's tests start PostgreSQL in Docker.
dotnet_codebase() {
  local label="$1" tests="$2" include="$3"
  echo "▶ .NET: $label (threshold ${min}%)"
  if ! command -v dotnet >/dev/null 2>&1; then echo "  NOT MEASURED: dotnet is not installed"; worse 3; return; fi
  if [ ! -d "$tests" ]; then echo "  NOT MEASURED: $tests is missing"; worse 3; return; fi
  if [ "$label" = "API" ] && ! docker info >/dev/null 2>&1; then
    echo "  NOT MEASURED: Docker is not running (the API's tests need a real PostgreSQL)"; worse 3; return
  fi
  local out; out="$(mktemp)"
  if dotnet test "$tests" --nologo /p:CollectCoverage=true "/p:Include=\"$include\"" \
       '/p:ExcludeByFile="**/Data/Migrations/*.cs,**/obj/**/*.cs"' /p:Threshold="$min" /p:ThresholdType=line /p:ThresholdStat=total \
       /p:CoverletOutput="$(mktemp -d)/" >"$out" 2>&1; then
    grep -E '^\| (Module|ClaudeMonitor|Total)' "$out" | sed 's/^/  /'
    echo "  ✓ at or above ${min}%"
  elif grep -q 'below the specified' "$out"; then
    grep -E '^\| (Module|ClaudeMonitor|Total)|below the specified' "$out" | sed 's/^/  /'
    echo "  ✗ below ${min}%"; worse 1
  else
    grep -E 'Failed |error|Passed!|Failed!' "$out" | head -20 | sed 's/^/  /'
    echo "  ✗ the tests are red or did not build"; worse 1
  fi
  rm -f "$out"
}

if [ -z "$(git ls-files --cached --others --exclude-standard '*.csproj')" ]; then
  echo "▶ .NET"
  echo "  n/a: no .NET project yet"
else
  dotnet_codebase "API" tests/ClaudeMonitor.Api.Tests "[ClaudeMonitor.Api]*,[ClaudeMonitor.Contracts]*"
  dotnet_codebase "agent" tests/ClaudeMonitor.Agent.Tests "[cm-agent]*"
fi

echo "▶ web"
if [ -z "$(git ls-files --cached --others --exclude-standard 'web/package.json')" ]; then
  echo "  n/a: no web app yet"
else
  echo "  NOT MEASURED: web/ exists but its coverage measurement is not written yet"
  worse 3
fi

exit "$status"
